//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    public partial class cArea : XPObject
    {
        string fdisplayName;
        public string displayName
        {
            get { return fdisplayName; }
            set { SetPropertyValue<string>(nameof(displayName), ref fdisplayName, value); }
        }
        int ftotalConfirmed;
        public int totalConfirmed
        {
            get { return ftotalConfirmed; }
            set { SetPropertyValue<int>(nameof(totalConfirmed), ref ftotalConfirmed, value); }
        }
        int ftotalDeaths;
        public int totalDeaths
        {
            get { return ftotalDeaths; }
            set { SetPropertyValue<int>(nameof(totalDeaths), ref ftotalDeaths, value); }
        }
        int ftotalRecovered;
        public int totalRecovered
        {
            get { return ftotalRecovered; }
            set { SetPropertyValue<int>(nameof(totalRecovered), ref ftotalRecovered, value); }
        }
        int ftotalActive;
        public int totalActive
        {
            get { return ftotalActive; }
            set { SetPropertyValue<int>(nameof(totalActive), ref ftotalActive, value); }
        }
        string fid;
        public string id
        {
            get { return fid; }
            set { SetPropertyValue<string>(nameof(id), ref fid, value); }
        }
        string fparentId;
        public string parentId
        {
            get { return fparentId; }
            set { SetPropertyValue<string>(nameof(parentId), ref fparentId, value); }
        }
        cDataPull fcDataPull;
        [Association(@"AreaReferencescDataPull")]
        public cDataPull cDataPull
        {
            get { return fcDataPull; }
            set { SetPropertyValue<cDataPull>(nameof(cDataPull), ref fcDataPull, value); }
        }
    }

}
