//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    public partial class cDataPull : XPObject
    {
        DateTime fPullDate;
        public DateTime PullDate
        {
            get { return fPullDate; }
            set { SetPropertyValue<DateTime>(nameof(PullDate), ref fPullDate, value); }
        }
        [Association(@"AreaReferencescDataPull")]
        public XPCollection<cArea> Areas { get { return GetCollection<cArea>(nameof(Areas)); } }
    }

}
