//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"HumanResources.EmployeeDepartmentHistory")]
    public partial class HumanResources_EmployeeDepartmentHistory : XPLiteObject
    {
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>(nameof(EndDate), ref fEndDate, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("BusinessEntityID")]
            public int BusinessEntityID { get; set; }
            [Persistent("DepartmentID")]
            public short DepartmentID { get; set; }
            [Persistent("ShiftID")]
            public byte ShiftID { get; set; }
            [Persistent("StartDate")]
            public DateTime StartDate { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
