//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"HumanResources.EmployeePayHistory")]
    public partial class HumanResources_EmployeePayHistory : XPLiteObject
    {
        decimal fRate;
        public decimal Rate
        {
            get { return fRate; }
            set { SetPropertyValue<decimal>(nameof(Rate), ref fRate, value); }
        }
        byte fPayFrequency;
        public byte PayFrequency
        {
            get { return fPayFrequency; }
            set { SetPropertyValue<byte>(nameof(PayFrequency), ref fPayFrequency, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("BusinessEntityID")]
            public int BusinessEntityID { get; set; }
            [Persistent("RateChangeDate")]
            public DateTime RateChangeDate { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
