//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"HumanResources.Employee")]
    public partial class HumanResources_Employee : XPLiteObject
    {
        int fBusinessEntityID;
        [Key]
        public int BusinessEntityID
        {
            get { return fBusinessEntityID; }
            set { SetPropertyValue<int>(nameof(BusinessEntityID), ref fBusinessEntityID, value); }
        }
        string fNationalIDNumber;
        [Indexed(Name = @"AK_Employee_NationalIDNumber", Unique = true)]
        [Size(15)]
        public string NationalIDNumber
        {
            get { return fNationalIDNumber; }
            set { SetPropertyValue<string>(nameof(NationalIDNumber), ref fNationalIDNumber, value); }
        }
        string fLoginID;
        [Indexed(Name = @"AK_Employee_LoginID", Unique = true)]
        [Size(256)]
        public string LoginID
        {
            get { return fLoginID; }
            set { SetPropertyValue<string>(nameof(LoginID), ref fLoginID, value); }
        }
        short fOrganizationLevel;
        [Indexed(Name = @"IX_Employee_OrganizationLevel_OrganizationNode")]
        public short OrganizationLevel
        {
            get { return fOrganizationLevel; }
            set { SetPropertyValue<short>(nameof(OrganizationLevel), ref fOrganizationLevel, value); }
        }
        string fJobTitle;
        [Size(50)]
        public string JobTitle
        {
            get { return fJobTitle; }
            set { SetPropertyValue<string>(nameof(JobTitle), ref fJobTitle, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value); }
        }
        char fMaritalStatus;
        public char MaritalStatus
        {
            get { return fMaritalStatus; }
            set { SetPropertyValue<char>(nameof(MaritalStatus), ref fMaritalStatus, value); }
        }
        char fGender;
        public char Gender
        {
            get { return fGender; }
            set { SetPropertyValue<char>(nameof(Gender), ref fGender, value); }
        }
        DateTime fHireDate;
        public DateTime HireDate
        {
            get { return fHireDate; }
            set { SetPropertyValue<DateTime>(nameof(HireDate), ref fHireDate, value); }
        }
        bool fSalariedFlag;
        [ColumnDbDefaultValue("((1))")]
        public bool SalariedFlag
        {
            get { return fSalariedFlag; }
            set { SetPropertyValue<bool>(nameof(SalariedFlag), ref fSalariedFlag, value); }
        }
        short fVacationHours;
        [ColumnDbDefaultValue("((0))")]
        public short VacationHours
        {
            get { return fVacationHours; }
            set { SetPropertyValue<short>(nameof(VacationHours), ref fVacationHours, value); }
        }
        short fSickLeaveHours;
        [ColumnDbDefaultValue("((0))")]
        public short SickLeaveHours
        {
            get { return fSickLeaveHours; }
            set { SetPropertyValue<short>(nameof(SickLeaveHours), ref fSickLeaveHours, value); }
        }
        bool fCurrentFlag;
        [ColumnDbDefaultValue("((1))")]
        public bool CurrentFlag
        {
            get { return fCurrentFlag; }
            set { SetPropertyValue<bool>(nameof(CurrentFlag), ref fCurrentFlag, value); }
        }
        Guid frowguid;
        [Indexed(Name = @"AK_Employee_rowguid", Unique = true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid rowguid
        {
            get { return frowguid; }
            set { SetPropertyValue<Guid>(nameof(rowguid), ref frowguid, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        [Association(@"HumanResources_JobCandidateReferencesHumanResources_Employee")]
        public XPCollection<HumanResources_JobCandidate> HumanResources_JobCandidates { get { return GetCollection<HumanResources_JobCandidate>(nameof(HumanResources_JobCandidates)); } }
    }

}
