//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"Person.PersonPhone")]
    public partial class Person_PersonPhone : XPLiteObject
    {
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("BusinessEntityID")]
            public int BusinessEntityID { get; set; }
            [Size(25)]
            [Persistent("PhoneNumber")]
            public string PhoneNumber { get; set; }
            [Persistent("PhoneNumberTypeID")]
            public int PhoneNumberTypeID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
