//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"Person.BusinessEntityContact")]
    public partial class Person_BusinessEntityContact : XPLiteObject
    {
        Guid frowguid;
        [Indexed(Name = @"AK_BusinessEntityContact_rowguid", Unique = true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid rowguid
        {
            get { return frowguid; }
            set { SetPropertyValue<Guid>(nameof(rowguid), ref frowguid, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("BusinessEntityID")]
            public int BusinessEntityID { get; set; }
            [Persistent("PersonID")]
            public int PersonID { get; set; }
            [Persistent("ContactTypeID")]
            public int ContactTypeID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
