//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"Person.Person")]
    public partial class Person_Person : XPLiteObject
    {
        int fBusinessEntityID;
        [Key]
        public int BusinessEntityID
        {
            get { return fBusinessEntityID; }
            set { SetPropertyValue<int>(nameof(BusinessEntityID), ref fBusinessEntityID, value); }
        }
        string fPersonType;
        [Size(2)]
        public string PersonType
        {
            get { return fPersonType; }
            set { SetPropertyValue<string>(nameof(PersonType), ref fPersonType, value); }
        }
        bool fNameStyle;
        [ColumnDbDefaultValue("((0))")]
        public bool NameStyle
        {
            get { return fNameStyle; }
            set { SetPropertyValue<bool>(nameof(NameStyle), ref fNameStyle, value); }
        }
        string fTitle;
        [Size(8)]
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fFirstName;
        [Size(50)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fMiddleName;
        [Size(50)]
        public string MiddleName
        {
            get { return fMiddleName; }
            set { SetPropertyValue<string>(nameof(MiddleName), ref fMiddleName, value); }
        }
        string fLastName;
        [Indexed(@"FirstName;MiddleName", Name = @"IX_Person_LastName_FirstName_MiddleName")]
        [Size(50)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fSuffix;
        [Size(10)]
        public string Suffix
        {
            get { return fSuffix; }
            set { SetPropertyValue<string>(nameof(Suffix), ref fSuffix, value); }
        }
        int fEmailPromotion;
        [ColumnDbDefaultValue("((0))")]
        public int EmailPromotion
        {
            get { return fEmailPromotion; }
            set { SetPropertyValue<int>(nameof(EmailPromotion), ref fEmailPromotion, value); }
        }
        string fAdditionalContactInfo;
        [Size(SizeAttribute.Unlimited)]
        public string AdditionalContactInfo
        {
            get { return fAdditionalContactInfo; }
            set { SetPropertyValue<string>(nameof(AdditionalContactInfo), ref fAdditionalContactInfo, value); }
        }
        string fDemographics;
        [Size(SizeAttribute.Unlimited)]
        public string Demographics
        {
            get { return fDemographics; }
            set { SetPropertyValue<string>(nameof(Demographics), ref fDemographics, value); }
        }
        Guid frowguid;
        [Indexed(Name = @"AK_Person_rowguid", Unique = true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid rowguid
        {
            get { return frowguid; }
            set { SetPropertyValue<Guid>(nameof(rowguid), ref frowguid, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
    }

}
