//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"Person.StateProvince")]
    public partial class Person_StateProvince : XPLiteObject
    {
        int fStateProvinceID;
        [Key(true)]
        public int StateProvinceID
        {
            get { return fStateProvinceID; }
            set { SetPropertyValue<int>(nameof(StateProvinceID), ref fStateProvinceID, value); }
        }
        string fStateProvinceCode;
        [Indexed(@"CountryRegionCode", Name = @"AK_StateProvince_StateProvinceCode_CountryRegionCode", Unique = true)]
        [Size(3)]
        public string StateProvinceCode
        {
            get { return fStateProvinceCode; }
            set { SetPropertyValue<string>(nameof(StateProvinceCode), ref fStateProvinceCode, value); }
        }
        Person_CountryRegion fCountryRegionCode;
        [Size(3)]
        [Association(@"Person_StateProvinceReferencesPerson_CountryRegion")]
        public Person_CountryRegion CountryRegionCode
        {
            get { return fCountryRegionCode; }
            set { SetPropertyValue<Person_CountryRegion>(nameof(CountryRegionCode), ref fCountryRegionCode, value); }
        }
        bool fIsOnlyStateProvinceFlag;
        [ColumnDbDefaultValue("((1))")]
        public bool IsOnlyStateProvinceFlag
        {
            get { return fIsOnlyStateProvinceFlag; }
            set { SetPropertyValue<bool>(nameof(IsOnlyStateProvinceFlag), ref fIsOnlyStateProvinceFlag, value); }
        }
        string fName;
        [Indexed(Name = @"AK_StateProvince_Name", Unique = true)]
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fTerritoryID;
        public int TerritoryID
        {
            get { return fTerritoryID; }
            set { SetPropertyValue<int>(nameof(TerritoryID), ref fTerritoryID, value); }
        }
        Guid frowguid;
        [Indexed(Name = @"AK_StateProvince_rowguid", Unique = true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid rowguid
        {
            get { return frowguid; }
            set { SetPropertyValue<Guid>(nameof(rowguid), ref frowguid, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        [Association(@"Person_AddressReferencesPerson_StateProvince")]
        public XPCollection<Person_Address> Person_Addresss { get { return GetCollection<Person_Address>(nameof(Person_Addresss)); } }
    }

}
