//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SandBox.Data
{

    [Persistent(@"Person.EmailAddress")]
    public partial class Person_EmailAddress : XPLiteObject
    {
        string fEmailAddress;
        [Indexed(Name = @"IX_EmailAddress_EmailAddress")]
        [Size(50)]
        public string EmailAddress
        {
            get { return fEmailAddress; }
            set { SetPropertyValue<string>(nameof(EmailAddress), ref fEmailAddress, value); }
        }
        Guid frowguid;
        [ColumnDbDefaultValue("(newid())")]
        public Guid rowguid
        {
            get { return frowguid; }
            set { SetPropertyValue<Guid>(nameof(rowguid), ref frowguid, value); }
        }
        DateTime fModifiedDate;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime ModifiedDate
        {
            get { return fModifiedDate; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedDate), ref fModifiedDate, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("BusinessEntityID")]
            public int BusinessEntityID { get; set; }
            [Persistent("EmailAddressID")]
            public int EmailAddressID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
